#!/bin/bash

# WiFi Setup Script for Portal LED Controller
# This script helps you securely configure WiFi credentials

echo "🌀 Portal LED Controller - WiFi Setup"
echo "======================================"

# Check if wifi_credentials.h already exists
if [ -f "wifi_credentials.h" ]; then
    echo "⚠️  wifi_credentials.h already exists."
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# Get WiFi credentials from user
echo
echo "Please enter your WiFi credentials:"
read -p "WiFi Network Name (SSID): " wifi_ssid
read -s -p "WiFi Password: " wifi_password
echo
echo
read -p "Access Point Name (default: PortalController): " ap_ssid
ap_ssid=${ap_ssid:-PortalController}
read -s -p "Access Point Password (default: portal123): " ap_password
ap_password=${ap_password:-portal123}
echo

# Create the credentials file
cat > wifi_credentials.h << EOF
#pragma once

/**
 * @file wifi_credentials.h
 * @brief WiFi credentials configuration
 *
 * This file contains your actual WiFi credentials and is git-ignored for security.
 * Generated by setup_wifi.sh script.
 */

// WiFi Network Credentials
#define WIFI_SSID "$wifi_ssid"
#define WIFI_PASSWORD "$wifi_password"

// Access Point credentials (if WiFi connection fails)
#define AP_SSID "$ap_ssid"
#define AP_PASSWORD "$ap_password"
EOF

echo "✅ WiFi credentials saved to wifi_credentials.h"
echo "🔒 This file is git-ignored for security"
echo
echo "Next steps:"
echo "1. Enable WiFi in src/config.h: #define ENABLE_WIFI_CONTROL 1"
echo "2. Build and upload: pio run -e d1 -t upload"
echo "3. Check serial monitor for the device IP address"
echo
echo "🌐 Your portal will be accessible at http://[device-ip]/"