name: outtatimers-implant
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pynng
  - protobuf # Installs as google.protobuf - use 'from google import protobuf'
  - pathlib2
  - typing-extensions
  - colorama
  - rich
  - tqdm
  - skidl>=2.0.0 # Python library for electronic circuit design and KiCad netlist generation
  - pip:
      - pytest
      - pytest-cov
      - black
      - flake8
      - sphinx
      - sphinx-rtd-theme
